// ---------- Seed data (Hertz Architects, Vadodara). All names/figures fictional. ----------
export const TODAY = "2026-09-09";
export const ROLES = {
  partner: { label: "Partner", desc: "Portfolio, approvals, rooms, costs" },
  designer: { label: "Designer", desc: "Tasks, R&D, client references" },
  site_manager: { label: "Site manager", desc: "One site, many contractors" },
  hr: { label: "HR / Ops", desc: "Leave, attendance, payroll calc" },
  client: { label: "Client", desc: "Progress, references, approvals" },
  contractor: { label: "Contractor", desc: "Scoped invite, one site only" },
};
export const USERS = [
  {
    id: "u1",
    name: "Harshal Patel",
    role: "partner",
    title: "Principal Partner",
    ini: "HP",
    skills: ["residential", "concept"],
    pts: 1240,
    streak: 31,
    quiet: false,
  },
  {
    id: "u2",
    name: "Ronak Kambodia",
    role: "partner",
    title: "Partner · Business",
    ini: "RK",
    skills: ["commercial", "approvals"],
    pts: 980,
    streak: 12,
    quiet: true,
  },
  {
    id: "u3",
    name: "Tushar Mhaiskar",
    role: "partner",
    title: "Partner · Interiors",
    ini: "TM",
    skills: ["interiors", "materials"],
    pts: 1105,
    streak: 22,
    quiet: false,
  },
  {
    id: "u4",
    name: "Zain Nizami",
    role: "partner",
    title: "Partner · Execution",
    ini: "ZN",
    skills: ["execution", "structure"],
    pts: 870,
    streak: 5,
    quiet: false,
  },
  {
    id: "u5",
    name: "Priya Shah",
    role: "designer",
    title: "Senior Designer",
    ini: "PS",
    skills: ["interiors", "kitchen", "joinery"],
    pts: 1460,
    streak: 44,
    quiet: false,
  },
  {
    id: "u6",
    name: "Nikhil Joshi",
    role: "designer",
    title: "Architect",
    ini: "NJ",
    skills: ["structure", "drawings", "concept"],
    pts: 1320,
    streak: 9,
    quiet: false,
  },
  {
    id: "u7",
    name: "Sana Pathan",
    role: "designer",
    title: "Junior Designer",
    ini: "SP",
    skills: ["3d", "moodboard", "interiors"],
    pts: 760,
    streak: 18,
    quiet: false,
  },
  {
    id: "u8",
    name: "Dhruv Patel",
    role: "designer",
    title: "Architect",
    ini: "DP",
    skills: ["drawings", "structure", "execution"],
    pts: 1010,
    streak: 2,
    quiet: false,
  },
  {
    id: "u9",
    name: "Meera Iyer",
    role: "designer",
    title: "Interior Designer",
    ini: "MI",
    skills: ["interiors", "kitchen", "materials"],
    pts: 1180,
    streak: 27,
    quiet: true,
  },
  {
    id: "u10",
    name: "Rohan Gandhi",
    role: "site_manager",
    title: "Site Manager · Alkapuri",
    ini: "RG",
    skills: ["execution", "snags"],
    pts: 1530,
    streak: 38,
    quiet: false,
  },
  {
    id: "u11",
    name: "Farhan Sheikh",
    role: "site_manager",
    title: "Site Manager · Ahmedabad",
    ini: "FS",
    skills: ["execution", "mep"],
    pts: 1290,
    streak: 15,
    quiet: false,
  },
  {
    id: "u12",
    name: "Bhavna Rao",
    role: "hr",
    title: "HR & Operations",
    ini: "BR",
    skills: ["ops"],
    pts: 640,
    streak: 52,
    quiet: false,
  },
  {
    id: "c1",
    name: "Anjali Jagwani",
    role: "client",
    title: "Client · Jagwani Residence",
    ini: "AK",
    projectIds: ["p1"],
  },
  {
    id: "c3",
    name: "Nilesh Trivedi",
    role: "client",
    title: "Prospect · G+1 bungalow",
    ini: "NT",
    projectIds: [],
    fromEnquiry: "e3",
  },
  {
    id: "c2",
    name: "Vivek Sanghvi",
    role: "client",
    title: "Client · Curators Café",
    ini: "VS",
    projectIds: ["p2"],
  },
  {
    id: "x1",
    name: "Om Civil Works",
    role: "contractor",
    title: "Civil contractor",
    ini: "OC",
    siteIds: ["s1"],
  },
  {
    id: "x2",
    name: "Sparkline Electricals",
    role: "contractor",
    title: "Electrical agency",
    ini: "SE",
    siteIds: ["s1"],
  },
  {
    id: "x3",
    name: "Woodcraft Joinery",
    role: "contractor",
    title: "Joinery vendor",
    ini: "WJ",
    siteIds: ["s2"],
  },
];
export const PHASES = [
  "Concept",
  "Design development",
  "Approvals",
  "Execution",
  "Handover",
];
export const PROJECTS = [
  {
    id: "p1",
    driveFolder: "https://drive.google.com/drive/folders/hertz-HA-2401",
    canvaDeck: "https://www.canva.com/design/hertz-HA-2401-concept",
    billState: "Gujarat",
    code: "HA-2401",
    name: "Jagwani Residence",
    kind: "Residential · Villa",
    area: "4,800 sq ft",
    city: "Alkapuri, Vadodara",
    clientId: "c1",
    siteId: "s1",
    phase: 3,
    teamIds: ["u1", "u5", "u6", "u10", "u9"],
    hue: 28,
    budget: 18500000,
    actual: 12140000,
    start: "2025-11-03",
    handover: "2027-02-15",
    milestones: [
      {
        id: "m1",
        name: "Concept sign-off",
        date: "2025-12-20",
        done: true,
        clientVisible: true,
      },
      {
        id: "m2",
        name: "DD drawings issued",
        date: "2026-03-14",
        done: true,
        clientVisible: true,
      },
      {
        id: "m3",
        name: "VMC plan approval",
        date: "2026-05-02",
        done: true,
        clientVisible: true,
      },
      {
        id: "m4",
        name: "Slab 2 casting",
        date: "2026-09-18",
        done: false,
        clientVisible: true,
      },
      {
        id: "m5",
        name: "Kitchen joinery order",
        date: "2026-09-25",
        done: false,
        clientVisible: true,
      },
      {
        id: "m6",
        name: "Internal cost review Q3",
        date: "2026-09-30",
        done: false,
        clientVisible: false,
      },
      {
        id: "m6b",
        name: "Griha pravesh (muhurat)",
        date: "2027-02-11",
        done: false,
        clientVisible: true,
        muhurat: true,
      },
    ],
    // Vastu notes: architect fills, client reads. Text only, no logic.
    vastu: [
      { room: "Kitchen", note: "South-east corner, cooking facing east. Client's panditji confirmed 12 Aug." },
      { room: "Master bedroom", note: "South-west, bed head to south. Avoid mirror facing bed." },
      { room: "Pooja", note: "North-east niche off living, no toilet above (checked first floor plan)." },
    ],
    drawings: [
      {
        no: "HA-2401-A-101",
        name: "Ground floor plan",
        rev: "R4",
        date: "2026-08-28",
        status: "Issued for construction",
        by: "u6",
      },
      {
        no: "HA-2401-A-102",
        name: "First floor plan",
        rev: "R3",
        date: "2026-08-21",
        status: "Issued for construction",
        by: "u6",
      },
      {
        no: "HA-2401-I-201",
        name: "Kitchen joinery details",
        rev: "R2",
        date: "2026-09-04",
        status: "For client approval",
        by: "u5",
      },
      {
        no: "HA-2401-S-301",
        name: "Slab 2 reinforcement",
        rev: "R1",
        date: "2026-09-01",
        status: "Issued for construction",
        by: "u8",
      },
      {
        no: "HA-2401-I-205",
        name: "Master bedroom wardrobe",
        rev: "R1",
        date: "2026-09-07",
        status: "Draft",
        by: "u9",
      },
    ],
    rnd: [
      {
        id: "r1",
        name: "Kota stone vs. Jaisalmer for courtyard",
        status: "Samples on site",
        owner: "u9",
        clientVisible: true,
      },
      {
        id: "r2",
        name: "Rain-water harvesting tank sizing",
        status: "Awaiting structural note",
        owner: "u8",
        clientVisible: true,
      },
    ],
    decisions: [
      "Courtyard paving: Kota stone, leather finish (25 Aug)",
      "Kitchen: island layout option B (2 Sep)",
    ],
    budgetLines: [
      { head: "Civil & structure", budget: 7200000, actual: 6100000 },
      { head: "Interiors & joinery", budget: 5400000, actual: 2900000 },
      { head: "MEP", budget: 2600000, actual: 1740000 },
      { head: "Landscape", budget: 1300000, actual: 200000 },
      { head: "Fees & approvals", budget: 2000000, actual: 1200000 },
    ],
  },
  {
    id: "p2",
    driveFolder: "https://drive.google.com/drive/folders/hertz-HA-2407",
    canvaDeck: "https://www.canva.com/design/hertz-HA-2407-concept",
    billState: "Gujarat",
    code: "HA-2407",
    name: "Curators Café",
    kind: "Commercial · Café",
    area: "12,000 sq ft",
    city: "Prahladnagar, Ahmedabad",
    clientId: "c2",
    siteId: "s2",
    phase: 3,
    teamIds: ["u2", "u4", "u8", "u11", "u7"],
    hue: 200,
    budget: 31000000,
    actual: 9800000,
    start: "2026-02-10",
    handover: "2027-06-30",
    milestones: [
      {
        id: "m7",
        name: "Concept sign-off",
        date: "2026-03-28",
        done: true,
        clientVisible: true,
      },
      {
        id: "m8",
        name: "Fire NOC",
        date: "2026-07-10",
        done: true,
        clientVisible: true,
      },
      {
        id: "m9",
        name: "Ceiling grid installation",
        date: "2026-09-22",
        done: false,
        clientVisible: true,
      },
      {
        id: "m10",
        name: "Furniture vendor shortlist",
        date: "2026-10-05",
        done: false,
        clientVisible: true,
      },
      {
        id: "m10b",
        name: "Bhoomi pujan (muhurat)",
        date: "2026-02-14",
        done: true,
        clientVisible: true,
        muhurat: true,
      },
    ],
    vastu: [
      { room: "Main entrance", note: "North facing, door opens clockwise. Client asked for threshold step." },
    ],
    drawings: [
      {
        no: "HA-2407-A-101",
        name: "Typical floor plan",
        rev: "R5",
        date: "2026-08-30",
        status: "Issued for construction",
        by: "u8",
      },
      {
        no: "HA-2407-I-210",
        name: "Reception desk detail",
        rev: "R2",
        date: "2026-09-03",
        status: "For client approval",
        by: "u7",
      },
      {
        no: "HA-2407-E-401",
        name: "Lighting layout L2",
        rev: "R1",
        date: "2026-09-06",
        status: "Draft",
        by: "u8",
      },
    ],
    rnd: [
      {
        id: "r3",
        name: "Acoustic baffles: felt vs wood",
        status: "Cost comparison in progress",
        owner: "u7",
        clientVisible: true,
      },
    ],
    decisions: ["Open-plan with 4 focus pods (12 Jun)"],
    budgetLines: [
      { head: "Civil & structure", budget: 9000000, actual: 4100000 },
      { head: "Interiors & joinery", budget: 12000000, actual: 3200000 },
      { head: "MEP & HVAC", budget: 7500000, actual: 2100000 },
      { head: "Fees & approvals", budget: 2500000, actual: 400000 },
    ],
  },
  {
    id: "p3",
    billState: "Gujarat",
    code: "HA-2412",
    name: "Gonpale Villa",
    kind: "Residential · Villa",
    area: "6,200 sq ft",
    city: "Billimora",
    clientId: null,
    siteId: null,
    phase: 1,
    teamIds: ["u3", "u9", "u7"],
    hue: 95,
    budget: 22000000,
    actual: 600000,
    start: "2026-08-01",
    handover: "2028-01-15",
    milestones: [
      {
        id: "m11",
        name: "Concept presentation",
        date: "2026-09-26",
        done: false,
        clientVisible: true,
      },
    ],
    drawings: [
      {
        no: "HA-2412-A-001",
        name: "Site analysis",
        rev: "R0",
        date: "2026-08-22",
        status: "Draft",
        by: "u9",
      },
    ],
    rnd: [
      {
        id: "r4",
        name: "Rammed earth feasibility",
        status: "Vendor visit booked",
        owner: "u3",
        clientVisible: true,
      },
    ],
    decisions: [],
    budgetLines: [
      { head: "Fees & approvals", budget: 2400000, actual: 600000 },
    ],
  },
  {
    id: "p4",
    billState: "Maharashtra", // client billed via Mumbai office, so IGST
    code: "HA-2318",
    name: "Mehta Clinic",
    kind: "Commercial · Healthcare",
    area: "3,100 sq ft",
    city: "Fatehgunj",
    clientId: null,
    siteId: null,
    phase: 4,
    teamIds: ["u2", "u6"],
    hue: 340,
    budget: 9200000,
    actual: 9350000,
    start: "2025-04-14",
    handover: "2026-08-30",
    milestones: [
      {
        id: "m12",
        name: "Handover & snag closure",
        date: "2026-08-30",
        done: true,
        clientVisible: true,
      },
    ],
    drawings: [],
    rnd: [],
    decisions: ["Handover accepted with 3 open snags (30 Aug)"],
    budgetLines: [
      { head: "Civil & interiors", budget: 9200000, actual: 9350000 },
    ],
  },
];
export const SITES = [
  {
    id: "s1",
    projectId: "p1",
    name: "Jagwani Residence site",
    managerId: "u10",
    contractorIds: ["x1", "x2"],
    progress: 58,
    hue: 28,
    stage: "Slab 2 shuttering",
    lastVisit: "2026-09-08",
    pettyCash: 25000, // float handed to site manager on 1 Sep, cash bills draw it down
  },
  {
    id: "s2",
    projectId: "p2",
    name: "Curators Café site",
    managerId: "u11",
    contractorIds: ["x3"],
    progress: 31,
    hue: 200,
    stage: "Ceiling grid",
    lastVisit: "2026-09-07",
  },
];
export const FEED = [
  {
    id: "f1",
    siteId: "s1",
    type: "photo",
    by: "u10",
    at: "2026-09-09T08:42",
    text: "Slab 2 shuttering 80% done. Column C4 rebar ready for check.",
    tags: ["slab", "rebar", "C4"],
    hue: 28,
    seed: 3,
  },
  {
    id: "f2",
    siteId: "s1",
    type: "voice",
    by: "u10",
    at: "2026-09-09T08:47",
    dur: "0:41",
    transcript:
      "Kitchen window opening on the north wall is coming 1,050 wide on site, drawing says 1,200. Mason says the column shifted. Need Priya to confirm before we cast lintel tomorrow.",
    aiSummary:
      "Kitchen north window opening is 150 mm narrower than drawing HA-2401-A-101 (1,050 vs 1,200). Lintel casting due tomorrow. Needs designer confirmation.",
    aiIssue: {
      type: "Measurement change",
      drawing: "HA-2401-A-101",
      sla: "24 h",
      title: "Kitchen north window 150 mm narrower than drawing",
    },
  },
  {
    id: "f2v",
    siteId: "s1",
    type: "video",
    by: "u10",
    at: "2026-09-09T08:44",
    dur: "0:36",
    hue: 200,
    seed: 7,
    transcript: "Walkthrough of slab 2 shuttering from grid A to D. Props at C3 look under-tightened.",
    aiSummary: "Slab 2 shuttering walkthrough, grid A to D. Props at C3 may need tightening before pour.",
    text: "Quick walkthrough before the pour.",
  },
  {
    id: "f3",
    siteId: "s1",
    type: "log",
    by: "x1",
    at: "2026-09-08T18:10",
    text: "Daily log · Om Civil: 14 workers. Shuttering slab 2 (grid A to D). Steel binding C1 to C4. Cement 40 bags used.",
    contractor: true,
  },
  {
    id: "f4",
    siteId: "s1",
    type: "photo",
    by: "x2",
    at: "2026-09-08T16:30",
    text: "Conduit layout ground floor living. Awaiting drawing for TV wall points.",
    tags: ["conduit", "electrical", "living"],
    hue: 200,
    seed: 7,
    contractor: true,
  },
  {
    id: "f5",
    siteId: "s1",
    type: "note",
    by: "u5",
    at: "2026-09-08T11:05",
    text: "Kota stone samples (leather + honed) placed near courtyard. Client visit Sat 10:30.",
  },
  {
    id: "f6",
    siteId: "s1",
    type: "photo",
    by: "u10",
    at: "2026-09-07T09:15",
    text: "Kota samples in morning light.",
    tags: ["kota", "sample", "courtyard"],
    hue: 40,
    seed: 11,
    dupOf: "f7",
  },
  {
    id: "f7",
    siteId: "s1",
    type: "photo",
    by: "u10",
    at: "2026-09-07T09:14",
    text: "Kota samples.",
    tags: ["kota", "sample", "courtyard"],
    hue: 40,
    seed: 11,
  },
  {
    id: "f8",
    siteId: "s2",
    type: "photo",
    by: "u11",
    at: "2026-09-08T17:40",
    text: "Ceiling grid L2 east wing. Sprinkler drops clash with baffle line near column E5.",
    tags: ["ceiling", "sprinkler", "E5"],
    hue: 200,
    seed: 5,
  },
  {
    id: "f9",
    siteId: "s2",
    type: "log",
    by: "x3",
    at: "2026-09-08T18:30",
    text: "Daily log · Woodcraft: reception desk carcass in workshop. Veneer sample sent for approval.",
    contractor: true,
  },
  {
    id: "f10",
    siteId: "s2",
    type: "voice",
    by: "u11",
    at: "2026-09-08T12:02",
    dur: "1:12",
    transcript:
      "HVAC duct at grid E5 is 120 lower than ceiling plan, so the baffle line will hit it. Either we drop the baffles in that bay or reroute the duct. Need an answer by Thursday or the grid crew idles.",
    aiSummary:
      "HVAC duct at E5 sits 120 mm below ceiling plan; conflicts with acoustic baffle line. Decision needed by Thu 11 Sep or grid crew idles.",
    aiIssue: {
      type: "Status blocker",
      drawing: "HA-2407-A-101",
      sla: "48 h",
      title: "Duct vs. baffle clash at E5",
    },
  },
];
export const ISSUES = [
  {
    id: "i1",
    siteId: "s1",
    projectId: "p1",
    title: "Kitchen north window 150 mm narrower than drawing",
    type: "Measurement change",
    drawing: "HA-2401-A-101",
    sla: "24 h",
    raisedBy: "u10",
    at: "2026-09-09T08:50",
    status: "open",
    assignee: "u5",
    due: "2026-09-10T08:50",
    source: "f2",
    updates: [
      {
        by: "u10",
        at: "2026-09-09T08:50",
        text: "Raised from voice note. Lintel cast tomorrow.",
      },
    ],
  },
  {
    id: "i2",
    siteId: "s2",
    projectId: "p2",
    title: "Duct vs. baffle clash at E5",
    type: "Status blocker",
    drawing: "HA-2407-A-101",
    sla: "48 h",
    raisedBy: "u11",
    at: "2026-09-08T12:10",
    status: "in_review",
    assignee: "u8",
    due: "2026-09-10T12:10",
    source: "f10",
    updates: [
      {
        by: "u11",
        at: "2026-09-08T12:10",
        text: "Raised. Grid crew idles Thu if unresolved.",
      },
      {
        by: "u8",
        at: "2026-09-08T15:30",
        text: "Checking with HVAC consultant. Likely drop baffles in bay E5 to E6.",
      },
    ],
  },
  {
    id: "i3",
    siteId: "s1",
    projectId: "p1",
    title: "TV wall conduit points missing on drawing",
    type: "Drawing request",
    drawing: "HA-2401-E-101",
    sla: "72 h",
    raisedBy: "x2",
    at: "2026-09-08T16:35",
    status: "open",
    assignee: "u6",
    due: "2026-09-11T16:35",
    updates: [],
  },
  {
    id: "i4",
    siteId: "s1",
    projectId: "p1",
    title: "Staircase riser height mismatch (170 vs 165)",
    type: "Measurement change",
    drawing: "HA-2401-A-101",
    sla: "24 h",
    raisedBy: "u10",
    at: "2026-09-02T10:00",
    status: "closed",
    assignee: "u6",
    due: "2026-09-03T10:00",
    closedAt: "2026-09-02T16:20",
    verifiedBy: "u1",
    updates: [
      {
        by: "u6",
        at: "2026-09-02T14:00",
        text: "Revised to 165 across 18 risers. R4 issued.",
      },
      {
        by: "u1",
        at: "2026-09-02T16:20",
        text: "Verified closure on site photo.",
      },
    ],
  },
];
export const SNAGS = [
  {
    id: "n1",
    siteId: "s1",
    text: "Plaster crack above door D3, first floor",
    status: "open",
    by: "u10",
    contractorId: "x1",
  },
  {
    id: "n2",
    siteId: "s1",
    text: "Conduit exposed at living wall point 4",
    status: "fixed",
    by: "u10",
    contractorId: "x2",
  },
  {
    id: "n3",
    siteId: "s2",
    text: "Grid tile misaligned E4 to E5",
    status: "open",
    by: "u11",
    contractorId: null,
  },
];
export const MATERIALS = [
  {
    id: "mt1",
    siteId: "s1",
    projectId: "p1",
    name: "Kota stone, leather finish",
    vendor: "Rajasthan Stone Co.",
    status: "client_pending",
    clientVisible: true,
    hue: 40,
    seed: 11,
  },
  {
    id: "mt2",
    siteId: "s1",
    projectId: "p1",
    name: "Kitchen laminate, walnut matte",
    vendor: "Merino",
    status: "approved",
    clientVisible: true,
    hue: 25,
    seed: 4,
  },
  {
    id: "mt3",
    siteId: "s2",
    projectId: "p2",
    name: "Reception veneer, smoked oak",
    vendor: "Woodcraft",
    status: "client_pending",
    clientVisible: true,
    hue: 30,
    seed: 9,
  },
  {
    id: "mt4",
    siteId: "s2",
    projectId: "p2",
    name: "Carpet tile, charcoal loop",
    vendor: "Interface",
    status: "internal_review",
    clientVisible: false,
    hue: 210,
    seed: 2,
  },
];
export const THREADS = [
  {
    id: "t1",
    projectId: "p1",
    name: "Jagwani Residence · Client",
    kind: "client",
    memberIds: ["c1", "u5", "u1", "u9"],
  },
  {
    id: "t2",
    projectId: "p1",
    name: "Jagwani Residence · Studio",
    kind: "internal",
    memberIds: ["u1", "u5", "u6", "u9", "u10"],
  },
  {
    id: "t3",
    projectId: "p2",
    name: "Curators Café · Client",
    kind: "client",
    memberIds: ["c2", "u7", "u2", "u4"],
  },
  {
    id: "t4",
    projectId: "p2",
    name: "Curators Café · Studio",
    kind: "internal",
    memberIds: ["u2", "u4", "u7", "u8", "u11"],
  },
  {
    id: "t5",
    projectId: "p1",
    name: "Jagwani site · Om Civil",
    kind: "site",
    siteId: "s1",
    memberIds: ["u10", "x1", "u6"],
  },
];
export const MESSAGES = [
  {
    id: "g1",
    threadId: "t1",
    by: "c1",
    at: "2026-09-07T20:15",
    text: "Loved this kitchen island. Can we do something like this?",
    link: {
      src: "Instagram",
      title: "Terrazzo island with brass inlay",
      by: "@studio.sepia",
      hue: 20,
      seed: 8,
    },
    filed: true,
  },
  {
    id: "g2",
    threadId: "t1",
    by: "u5",
    at: "2026-09-08T09:30",
    text: "Yes, terrazzo top works with option B. Two options for the base below. Brass inlay adds about ₹45,000; polished concrete base saves about ₹20,000.",
    options: [
      "Brass inlay, terrazzo top",
      "Polished concrete base, terrazzo top",
    ],
  },
  {
    id: "g3",
    threadId: "t1",
    by: "c1",
    at: "2026-09-08T10:02",
    text: "Option 1 please. Also this pantry from Pinterest.",
    link: {
      src: "Pinterest",
      title: "Fluted oak pantry doors",
      by: "Pin · Nordic Kitchens",
      hue: 35,
      seed: 12,
    },
    filed: true,
  },
  {
    id: "g4",
    threadId: "t1",
    by: "u5",
    at: "2026-09-08T10:20",
    text: "Decision: Kitchen island: brass inlay, terrazzo top (option 1). Filed to moodboard.",
    pinned: true,
    decision: true,
  },
  {
    id: "g5",
    threadId: "t1",
    by: "u5",
    at: "2026-09-08T11:10",
    text: "Kota stone samples are on site. Can you visit Saturday 10:30? Please approve the leather finish here when you see it.",
    approval: { id: "mt1", label: "Approve Kota stone, leather finish" },
  },
  {
    id: "g6",
    threadId: "t1",
    by: "c1",
    at: "2026-09-08T18:45",
    text: "Saturday works. Also, how are we on the courtyard tank?",
    link: {
      src: "YouTube",
      title: "Rainwater harvesting for villas, 12 min",
      by: "GreenHome India",
      hue: 120,
      seed: 6,
    },
    filed: false,
  },
  {
    id: "g7",
    threadId: "t2",
    by: "u10",
    at: "2026-09-09T08:52",
    text: "Raised issue: kitchen north window 150 mm narrow. Lintel tomorrow. Priya please confirm.",
    issueId: "i1",
  },
  {
    id: "g8",
    threadId: "t2",
    by: "u5",
    at: "2026-09-09T09:05",
    text: "Looking now. If the column moved, we can lose 150 from the fixed panel and keep the operable sash at 600.",
  },
  {
    id: "g9",
    threadId: "t3",
    by: "u7",
    at: "2026-09-06T15:00",
    text: "Reception desk detail R2 shared. Veneer options attached.",
  },
  {
    id: "g10",
    threadId: "t3",
    by: "c2",
    at: "2026-09-06T19:30",
    text: "Smoked oak looks right. Approve from my side once I see the physical sample.",
  },
  {
    id: "g11",
    threadId: "t5",
    by: "u10",
    at: "2026-09-08T18:20",
    text: "Tomorrow: finish shuttering A to D, keep C4 open for rebar check at 9.",
  },
  {
    id: "g12",
    threadId: "t5",
    by: "x1",
    at: "2026-09-08T18:25",
    text: "Noted. 14 workers confirmed.",
  },
];
export const MOODBOARD = [
  {
    id: "b1",
    projectId: "p1",
    title: "Terrazzo island, brass inlay",
    src: "Instagram",
    hue: 20,
    seed: 8,
    tall: true,
    decided: true,
  },
  {
    id: "b2",
    projectId: "p1",
    title: "Fluted oak pantry doors",
    src: "Pinterest",
    hue: 35,
    seed: 12,
  },
  {
    id: "b3",
    projectId: "p1",
    title: "Kota courtyard, leather finish",
    src: "Site photo",
    hue: 40,
    seed: 11,
    decided: true,
  },
  {
    id: "b4",
    projectId: "p1",
    title: "Lime-plaster living wall",
    src: "Pinterest",
    hue: 30,
    seed: 3,
    tall: true,
  },
  {
    id: "b5",
    projectId: "p1",
    title: "Cane-back dining chairs",
    src: "Instagram",
    hue: 45,
    seed: 14,
  },
  {
    id: "b6",
    projectId: "p2",
    title: "Felt acoustic baffles",
    src: "Pinterest",
    hue: 200,
    seed: 2,
  },
  {
    id: "b7",
    projectId: "p2",
    title: "Smoked oak reception",
    src: "Vendor sample",
    hue: 30,
    seed: 9,
    tall: true,
  },
];
export const ROOMS = [
  {
    id: "r1",
    name: "Meeting room",
    type: "room",
    location: "Office",
    cap: 8,
    exclusive: true,
    bookableBy: ["partner", "designer", "site_manager", "hr"],
    gear: "TV · whiteboard",
  },
];
// bookings on TODAY, hours as decimals (9 = 09:00)
export const BOOKINGS = [
  {
    id: "k1",
    roomId: "r1",
    date: "2026-09-09",
    start: 10,
    end: 11,
    title: "Weekly design review",
    by: "u1",
    attendees: ["u1", "u3", "u5", "u6", "u9"],
    kind: "review",
    recurring: "Weekly · Tue",
  },
  {
    id: "k2",
    roomId: "r1",
    date: "2026-09-09",
    start: 11.5,
    end: 12.5,
    title: "Curators veneer samples",
    by: "u2",
    attendees: ["u2", "u7", "c2"],
    kind: "client",
  },
  {
    id: "k3",
    roomId: "r1",
    date: "2026-09-09",
    start: 14,
    end: 15.5,
    title: "Q3 cost review",
    by: "u4",
    attendees: ["u1", "u2", "u3", "u4"],
    kind: "review",
  },
  {
    id: "k4",
    roomId: null,
    date: "2026-09-09",
    start: 15.5,
    end: 18,
    title: "Site visit · Jagwani slab 2",
    by: "u4",
    attendees: ["u4", "u10"],
    kind: "travel",
  },
  {
    id: "k5",
    roomId: null,
    date: "2026-09-09",
    start: 9,
    end: 10,
    title: "Harshal · calls",
    by: "u1",
    attendees: ["u1"],
    kind: "focus",
  },
  {
    id: "k6",
    roomId: "r1",
    date: "2026-09-10",
    start: 10.5,
    end: 11.5,
    title: "Jagwani Kota samples",
    by: "u5",
    attendees: ["u5", "c1", "u9"],
    kind: "client",
  },
];
export const LEAVES = [
  {
    id: "l1",
    userId: "u6",
    type: "Casual",
    from: "2026-09-15",
    to: "2026-09-16",
    days: 2,
    status: "pending",
    reason: "Family function",
    at: "2026-09-08",
  },
  {
    id: "l2",
    userId: "u7",
    type: "Sick",
    from: "2026-09-09",
    to: "2026-09-09",
    days: 1,
    status: "approved",
    reason: "Fever",
    at: "2026-09-09",
    approvedBy: "u12",
  },
  {
    id: "l3",
    userId: "u10",
    type: "Earned",
    from: "2026-10-01",
    to: "2026-10-04",
    days: 4,
    status: "pending",
    reason: "Travel",
    at: "2026-09-07",
  },
  {
    id: "l4",
    userId: "u9",
    type: "Casual",
    from: "2026-08-21",
    to: "2026-08-21",
    days: 1,
    status: "approved",
    reason: "Personal",
    at: "2026-08-18",
    approvedBy: "u12",
  },
];
export const BALANCES = {
  Casual: { total: 12, used: 4 },
  Sick: { total: 8, used: 2 },
  Earned: { total: 15, used: 3 },
};
// site: true = labour does not come, site plan skips the day. Seeded for Gujarat, editable in Settings.
export const HOLIDAYS = [
  { date: "2026-09-14", name: "Ganesh Visarjan (optional)" },
  { date: "2026-10-02", name: "Gandhi Jayanti" },
  { date: "2026-10-20", name: "Dussehra", site: true },
  { date: "2026-11-06", name: "Diwali shutdown starts", site: true },
  { date: "2026-11-07", name: "Diwali shutdown", site: true },
  { date: "2026-11-08", name: "Diwali", site: true },
  { date: "2026-11-09", name: "New Year (Bestu Varas)", site: true },
  { date: "2026-11-10", name: "Bhai Dooj", site: true },
  { date: "2026-11-11", name: "Labour returns (site half day)", site: true },
  { date: "2026-12-25", name: "Christmas" },
  { date: "2027-01-14", name: "Uttarayan", site: true },
  { date: "2027-01-15", name: "Vasi Uttarayan", site: true },
  { date: "2027-03-22", name: "Holi", site: true },
  { date: "2027-03-23", name: "Dhuleti", site: true },
];
export const ATTENDANCE_TODAY = [
  { userId: "u1", in: "09:04", out: null, mark: "ontime" },
  { userId: "u2", in: "09:38", out: null, mark: "late" },
  { userId: "u3", in: "08:55", out: null, mark: "ontime" },
  {
    userId: "u4",
    in: "09:10",
    out: null,
    mark: "ontime",
    note: "Site visit 15:30",
  },
  { userId: "u5", in: "09:01", out: null, mark: "ontime" },
  { userId: "u6", in: "09:12", out: null, mark: "ontime" },
  { userId: "u7", in: null, out: null, mark: "leave" },
  { userId: "u8", in: "09:47", out: null, mark: "late" },
  { userId: "u9", in: "13:05", out: null, mark: "half" },
  { userId: "u10", in: "08:20", out: null, mark: "ontime", note: "On site" },
  { userId: "u11", in: "08:35", out: null, mark: "ontime", note: "On site" },
  { userId: "u12", in: "08:58", out: null, mark: "ontime" },
];
export const SALARY = [
  {
    userId: "u5",
    base: 78000,
    presentDays: 22,
    halfDays: 1,
    lateMarks: 0,
    leaveDeduct: 0,
    hra: 15600,
    pf: 4680,
  },
  {
    userId: "u6",
    base: 62000,
    presentDays: 21,
    halfDays: 0,
    lateMarks: 2,
    leaveDeduct: 1,
    hra: 12400,
    pf: 3720,
  },
  {
    userId: "u7",
    base: 34000,
    presentDays: 20,
    halfDays: 2,
    lateMarks: 1,
    leaveDeduct: 0,
    hra: 6800,
    pf: 2040,
  },
  {
    userId: "u8",
    base: 60000,
    presentDays: 22,
    halfDays: 0,
    lateMarks: 4,
    leaveDeduct: 0,
    hra: 12000,
    pf: 3600,
  },
  {
    userId: "u9",
    base: 58000,
    presentDays: 21,
    halfDays: 3,
    lateMarks: 0,
    leaveDeduct: 0,
    hra: 11600,
    pf: 3480,
  },
  {
    userId: "u10",
    base: 55000,
    presentDays: 23,
    halfDays: 0,
    lateMarks: 0,
    leaveDeduct: 0,
    hra: 11000,
    pf: 3300,
  },
  {
    userId: "u11",
    base: 52000,
    presentDays: 22,
    halfDays: 0,
    lateMarks: 1,
    leaveDeduct: 0,
    hra: 10400,
    pf: 3120,
  },
  {
    userId: "u12",
    base: 45000,
    presentDays: 22,
    halfDays: 0,
    lateMarks: 0,
    leaveDeduct: 0,
    hra: 9000,
    pf: 2700,
  },
];
export const BADGES = [
  {
    id: "bd1",
    name: "Zero-rework drawing",
    icon: "✎",
    desc: "A drawing issued with no revision for 30 days",
    earnedBy: ["u6", "u8"],
  },
  {
    id: "bd2",
    name: "Fast closer",
    icon: "⚡",
    desc: "5 site issues closed within SLA",
    earnedBy: ["u10", "u5"],
  },
  {
    id: "bd3",
    name: "Early bird ×30",
    icon: "☀",
    desc: "30-day on-time check-in streak",
    earnedBy: ["u5", "u10", "u12", "u1"],
  },
  {
    id: "bd4",
    name: "Client hero",
    icon: "♡",
    desc: "Client decision turned around in under a day",
    earnedBy: ["u5"],
  },
  {
    id: "bd5",
    name: "Site scribe",
    icon: "✦",
    desc: "20 site logs with photos in a month",
    earnedBy: ["u10", "u11"],
  },
  {
    id: "bd6",
    name: "Mentor",
    icon: "◎",
    desc: "Reviewed 10 junior drawings",
    earnedBy: ["u6"],
  },
];
export const TEAM_GOAL = {
  name: "Q3 · Close 90% of site issues inside SLA",
  progress: 0.82,
  target: 0.9,
  ends: "2026-09-30",
};
// `status` stays the simple open/done flag every other page already reads ('open' means active,
// anything else is not). `stage` is the richer To do/In progress/Waiting/Review/Done the All
// Tasks board and task detail use; it's additive and never changes what svc.tasks()/svc.load()
// (and projects/TabsA.jsx, projects/Overview.jsx) already filter on. `priority` likewise sits
// alongside the existing `critical` boolean rather than replacing it. `checklist`/`blockedBy`/
// `blocks`/`description` are only on the tasks where the studio's own data (FEED/ISSUES) already
// tells this story — not invented for tasks that don't have one.
export const TASKS = [
  {
    id: "k01",
    projectId: "p1",
    title: "Confirm kitchen window revision",
    owner: "u5",
    due: "2026-09-10",
    status: "open",
    critical: true,
    issueId: "i1",
    priority: "critical",
    stage: "in_progress",
    description: "Kitchen north window opening came in 150 mm narrower on site than drawing HA-2401-A-101. Confirm with structural whether the lintel can still cast tomorrow, or revise the drawing first.",
    checklist: [
      { id: "k01c1", text: "Review site photo against drawing HA-2401-A-101", done: true },
      { id: "k01c2", text: "Confirm with structural (Zain)", done: false },
      { id: "k01c3", text: "Issue revised drawing if the opening stays at 1,050", done: false },
    ],
    blockedBy: ["k08"],
  },
  {
    id: "k02",
    projectId: "p1",
    title: "Wardrobe drawing I-205 to R1 issue",
    owner: "u9",
    due: "2026-09-12",
    status: "open",
    priority: "normal",
    stage: "todo",
    description: "Revise wardrobe drawing I-205 to R1 for the client's walnut veneer selection, then issue to site.",
  },
  {
    id: "k03",
    projectId: "p1",
    title: "TV wall electrical points",
    owner: "u6",
    due: "2026-09-11",
    status: "open",
    issueId: "i3",
    priority: "high",
    stage: "waiting",
    description: "Electrical points for the TV wall are missing from drawing HA-2401-E-101. Waiting on the updated drawing before the electrical contractor can mark out conduit.",
  },
  {
    id: "k04",
    projectId: "p2",
    title: "Resolve E5 duct / baffle clash",
    owner: "u8",
    due: "2026-09-10",
    status: "open",
    critical: true,
    issueId: "i2",
    priority: "critical",
    stage: "review",
    description: "HVAC duct at grid E5 sits 120 mm below the ceiling plan and conflicts with the acoustic baffle line. Decide: drop the baffles in bay E5–E6, or reroute the duct, before the grid crew idles.",
    checklist: [
      { id: "k04c1", text: "Get the HVAC consultant's measured clearance", done: true },
      { id: "k04c2", text: "Decide: drop baffle vs. reroute duct", done: false },
      { id: "k04c3", text: "Brief the site team on the decision", done: false },
    ],
    blocks: ["k05"],
  },
  {
    id: "k05",
    projectId: "p2",
    title: "Lighting layout L2 for review",
    owner: "u8",
    due: "2026-09-15",
    status: "open",
    priority: "normal",
    stage: "todo",
    description: "Lighting layout for level 2, held until the ceiling/baffle clash at grid E5 is decided.",
    blockedBy: ["k04"],
  },
  {
    id: "k06",
    projectId: "p3",
    title: "Concept boards ×3",
    owner: "u7",
    due: "2026-09-20",
    status: "open",
    critical: true,
    priority: "critical",
    stage: "in_progress",
    description: "Three concept boards for the Gonpale Villa client presentation — material palette, massing study, landscape direction.",
    checklist: [
      { id: "k06c1", text: "Material palette board", done: true },
      { id: "k06c2", text: "Massing study board", done: false },
      { id: "k06c3", text: "Landscape direction board", done: false },
    ],
  },
  {
    id: "k07",
    projectId: "p3",
    title: "Rammed-earth vendor visit",
    owner: "u3",
    due: "2026-09-17",
    status: "open",
    priority: "low",
    stage: "todo",
    description: "Site visit to the rammed-earth vendor's yard near Billimora to assess sample panels before specifying for Gonpale Villa.",
  },
  {
    id: "k08",
    projectId: "p1",
    title: "Slab 2 rebar check C4",
    owner: "u10",
    due: "2026-09-09",
    status: "open",
    priority: "high",
    stage: "review",
    description: "Column C4 rebar ready for check (see today's site log) before tomorrow's lintel and slab 2 pour.",
    blocks: ["k01"],
  },
];
export const AUDIT = [
  {
    at: "2026-09-08T10:20",
    by: "u5",
    what: "Decision pinned · Kitchen island option 1",
    entity: "Message g4",
  },
  {
    at: "2026-09-08T09:00",
    by: "u12",
    what: "Leave approved · Sana Pathan · Sick 1 day",
    entity: "LeaveRequest l2",
  },
  {
    at: "2026-09-05T17:30",
    by: "u1",
    what: "Budget line edited · Interiors & joinery 52L → 54L",
    entity: "Project p1",
  },
  {
    at: "2026-09-02T16:20",
    by: "u1",
    what: "Issue closure verified · i4",
    entity: "Issue i4",
  },
  {
    at: "2026-09-01T11:00",
    by: "u12",
    what: "Salary computation run · Aug 2026 · 8 employees",
    entity: "SalaryComputation 2026-08",
  },
];
// NAS mock filesystem fixture
export const NAS_TREE = {
  root: "/volume1/Projects",
  template: "{code} {name}/{phase}/{category}",
  entries: [
    {
      p: "HA-2401 Jagwani Residence",
      dir: true,
      map: "Project p1",
      c: [
        {
          p: "01 Concept",
          dir: true,
          map: "Phase: Concept",
          c: [
            { p: "Concept_v3.pdf", size: "18 MB", map: "MediaAsset" },
            {
              p: "Moodboard.key",
              size: "92 MB",
              map: "skip",
              why: "unsupported type",
            },
          ],
        },
        {
          p: "02 DD",
          dir: true,
          map: "Phase: Design development",
          c: [
            { p: "HA-2401-A-101_R4.dwg", size: "2.1 MB", map: "Drawing R4" },
            {
              p: "HA-2401-A-101_R3.dwg",
              size: "2.0 MB",
              map: "Drawing R3 (history)",
            },
            { p: "HA-2401-I-201_R2.pdf", size: "4.4 MB", map: "Drawing R2" },
          ],
        },
        {
          p: "04 Site",
          dir: true,
          map: "Site s1",
          c: [
            {
              p: "2026-09-08",
              dir: true,
              map: "Feed day",
              c: [
                {
                  p: "IMG_4412.jpg",
                  size: "3.2 MB",
                  map: "MediaAsset (dup of IMG_4411)",
                  warn: true,
                },
                { p: "IMG_4411.jpg", size: "3.2 MB", map: "MediaAsset" },
                {
                  p: "VN_0847.m4a",
                  size: "0.6 MB",
                  map: "MediaAsset · transcribe",
                },
              ],
            },
          ],
        },
        {
          p: "_app",
          dir: true,
          map: "App writes here",
          c: [
            { p: "2026-09-10_IMG_4411_kitchen.jpg", size: "3.2 MB", map: "MediaAsset", chat: true },
            { p: "2026-09-11_VN_0847_transcript.txt", size: "2 KB", map: "Voice note", chat: true },
            { p: "2026-09-11_material_bill_hardware.pdf", size: "180 KB", map: "Expense e2", chat: true },
          ],
        },
        {
          p: "Old stuff",
          dir: true,
          map: "unmapped",
          why: "no template match",
          c: [{ p: "quote_old.xlsx", size: "80 KB", map: "skip" }],
        },
      ],
    },
    {
      p: "HA-2407 Curators Café",
      dir: true,
      map: "Project p2",
      c: [
        {
          p: "02 DD",
          dir: true,
          map: "Phase: Design development",
          c: [{ p: "HA-2407-A-101_R5.dwg", size: "3.3 MB", map: "Drawing R5" }],
        },
        {
          p: "03 Approvals",
          dir: true,
          map: "Phase: Approvals",
          c: [{ p: "Fire_NOC.pdf", size: "1.1 MB", map: "MediaAsset" }],
        },
      ],
    },
    {
      p: "HA-2318 Mehta Clinic",
      dir: true,
      map: "Project p4",
      c: [
        {
          p: "05 Handover",
          dir: true,
          map: "Phase: Handover",
          c: [{ p: "Snag_list_final.pdf", size: "0.9 MB", map: "MediaAsset" }],
        },
      ],
    },
    {
      p: "Sanghvi tender (old name)",
      dir: true,
      map: "new",
      why: "no code prefix, will create Project?",
      c: [],
    },
  ],
  // Employee-wise share. ISO 19650 "work in progress": owner + partners read, app never writes.
  employees: {
    root: "/volume1/Employees",
    entries: [
      {
        p: "Priya Shah",
        dir: true,
        map: "Person u5",
        c: [
          {
            p: "WIP",
            dir: true,
            c: [
              { p: "HA-2401-A-102_wip.dwg", size: "1.8 MB" },
              { p: "HA-2401-I-202_draft.pdf", size: "4.1 MB" },
              { p: "kitchen_options_v2.skp", size: "22 MB" },
            ],
          },
          { p: "Reference", dir: true, c: [{ p: "joinery_details.pdf", size: "9 MB" }] },
        ],
      },
      {
        p: "Nikhil Joshi",
        dir: true,
        map: "Person u6",
        c: [{ p: "WIP", dir: true, c: [{ p: "HA-2407-A-105_wip.dwg", size: "2.4 MB" }] }],
      },
      {
        p: "Rohan Gandhi",
        dir: true,
        map: "Person u10",
        c: [{ p: "WIP", dir: true, c: [{ p: "site_photos_raw_2026-09-11", dir: true, c: [{ p: "IMG_4501.jpg", size: "3.4 MB" }] }] }],
      },
    ],
  },
};

// ---------- Org Leave & Holiday management (mock replacement for the former Postgres-backed
// packages/backend/src/routes/leave.ts, holiday.ts) ----------
// Frontend-only now: shapes mirror the old API responses exactly (leaveType/employee/approver
// nested objects, ISO date strings, `totalDays`, computed balance fields) so the screens that
// consume them (People.jsx "Leaves" tab, Schedule.jsx/dialogs.jsx "Holidays" tab) needed no
// changes beyond swapping the fetch client for a local one (see api/leaveClient.js). Separate
// from the older LEAVES/BALANCES/HOLIDAYS arrays above, which power the unrelated dashboard
// "pending leave" widget and the "push holiday notice" demo.
const ORG_ID = "hertz-demo";
export const ORG_LEAVE_TYPES = [
  { id: "lt1", organizationId: ORG_ID, name: "Casual Leave", paid: true, annualAllowance: 12, allowHalfDay: true, requiresApproval: true, active: true, createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z" },
  { id: "lt2", organizationId: ORG_ID, name: "Sick Leave", paid: true, annualAllowance: 8, allowHalfDay: true, requiresApproval: true, active: true, createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z" },
  { id: "lt3", organizationId: ORG_ID, name: "Earned Leave", paid: true, annualAllowance: 15, allowHalfDay: false, requiresApproval: true, active: true, createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z" },
  { id: "lt4", organizationId: ORG_ID, name: "Unpaid Leave", paid: false, annualAllowance: 0, allowHalfDay: true, requiresApproval: true, active: true, createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z" },
];
// Requests already resolved (used/pending) for the seeded employees (u1 partner, u5 designer,
// u10 site_manager, u12 hr - the four roles the RBAC matrix grants any "leave" access to).
export const ORG_LEAVE_REQUESTS = [
  { id: "lr1", organizationId: ORG_ID, employeeId: "u5", leaveTypeId: "lt1", startDate: "2026-08-10T00:00:00.000Z", endDate: "2026-08-11T00:00:00.000Z", halfDay: false, totalDays: 2, reason: "Family function", status: "approved", approverId: "u12", createdAt: "2026-08-01T09:00:00.000Z", updatedAt: "2026-08-02T10:00:00.000Z" },
  { id: "lr2", organizationId: ORG_ID, employeeId: "u5", leaveTypeId: "lt2", startDate: "2026-09-03T00:00:00.000Z", endDate: "2026-09-03T00:00:00.000Z", halfDay: false, totalDays: 1, reason: "Fever", status: "approved", approverId: "u12", createdAt: "2026-09-02T08:30:00.000Z", updatedAt: "2026-09-02T18:00:00.000Z" },
  { id: "lr3", organizationId: ORG_ID, employeeId: "u10", leaveTypeId: "lt1", startDate: "2026-09-20T00:00:00.000Z", endDate: "2026-09-20T00:00:00.000Z", halfDay: true, totalDays: 0.5, reason: "Personal work", status: "pending", approverId: null, createdAt: "2026-09-15T11:00:00.000Z", updatedAt: "2026-09-15T11:00:00.000Z" },
  { id: "lr4", organizationId: ORG_ID, employeeId: "u12", leaveTypeId: "lt3", startDate: "2026-10-05T00:00:00.000Z", endDate: "2026-10-07T00:00:00.000Z", halfDay: false, totalDays: 3, reason: "Diwali travel", status: "pending", approverId: null, createdAt: "2026-09-25T09:15:00.000Z", updatedAt: "2026-09-25T09:15:00.000Z" },
  { id: "lr5", organizationId: ORG_ID, employeeId: "u1", leaveTypeId: "lt2", startDate: "2026-07-14T00:00:00.000Z", endDate: "2026-07-14T00:00:00.000Z", halfDay: false, totalDays: 1, reason: "", status: "rejected", approverId: "u12", createdAt: "2026-07-13T07:00:00.000Z", updatedAt: "2026-07-13T19:00:00.000Z" },
  { id: "lr6", organizationId: ORG_ID, employeeId: "u5", leaveTypeId: "lt1", startDate: "2026-06-02T00:00:00.000Z", endDate: "2026-06-02T00:00:00.000Z", halfDay: false, totalDays: 1, reason: "Errand", status: "cancelled", approverId: null, createdAt: "2026-06-01T09:00:00.000Z", updatedAt: "2026-06-01T12:00:00.000Z" },
];
export const ORG_HOLIDAYS = [
  { id: "oh1", organizationId: ORG_ID, name: "Ganesh Visarjan (optional)", date: "2026-09-14T00:00:00.000Z", type: "optional", description: "", createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z" },
  { id: "oh2", organizationId: ORG_ID, name: "Gandhi Jayanti", date: "2026-10-02T00:00:00.000Z", type: "mandatory", description: "", createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z" },
  { id: "oh3", organizationId: ORG_ID, name: "Dussehra", date: "2026-10-20T00:00:00.000Z", type: "mandatory", description: "Office and site closed.", createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z" },
  { id: "oh4", organizationId: ORG_ID, name: "Diwali", date: "2026-11-08T00:00:00.000Z", type: "mandatory", description: "Studio holiday, ", createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z" },
  { id: "oh5", organizationId: ORG_ID, name: "Christmas", date: "2026-12-25T00:00:00.000Z", type: "mandatory", description: "", createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z" },
  { id: "oh6", organizationId: ORG_ID, name: "Holi", date: "2027-03-22T00:00:00.000Z", type: "optional", description: "", createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z" },
];
// Photo palettes for generated placeholder imagery, keyed by hue
