const ENGLISH = {
  chats: 'Chats',
  today: 'Today',
  projects: 'Projects',
  updates: 'Updates',
  message: 'Message',
  send: 'Send',
  photo: 'Photo',
  camera: 'Camera',
  voice: 'Voice note',
  drawing: 'Drawing',
  delivery: 'Delivery',
  sample: 'Sample',
  more: 'More',
  yes: 'Yes',
  ok: 'OK',
  onMyWay: 'On my way',
  clientGroup: 'Client group',
  group: 'Group',
  office: 'Office',
  siteTeam: 'Site team',
  chat: 'Chat',
  sendSitePhoto: 'Send a site photo',
  todayWord: 'Today',
  yesterday: 'Yesterday',
  officeOnly: 'Office only. The client never sees this.',
  people: 'people',
};

const PACKS = {
  English: ENGLISH,
  'हिन्दी': {
    ...ENGLISH,
    chats: 'चैट',
    today: 'आज',
    projects: 'प्रोजेक्ट',
    updates: 'अपडेट',
    message: 'संदेश',
    send: 'भेजें',
    photo: 'फोटो',
    camera: 'कैमरा',
    voice: 'वॉइस नोट',
    drawing: 'ड्राइंग',
    delivery: 'डिलीवरी',
    sample: 'सैंपल',
    more: 'और',
    yes: 'हाँ',
    ok: 'ठीक',
    onMyWay: 'आ रहा हूँ',
    clientGroup: 'क्लाइंट ग्रुप',
    office: 'ऑफिस',
    siteTeam: 'साइट टीम',
    chat: 'चैट',
    sendSitePhoto: 'साइट की फोटो भेजें',
    todayWord: 'आज',
    yesterday: 'कल',
    officeOnly: 'यह ऑफिस चैट है। क्लाइंट को नहीं दिखेगी।',
    people: 'लोग',
  },
  'ગુજરાતી': {
    ...ENGLISH,
    chats: 'ચેટ',
    today: 'આજે',
    projects: 'પ્રોજેક્ટ',
    updates: 'અપડેટ',
    message: 'સંદેશ',
    send: 'મોકલો',
    photo: 'ફોટો',
    camera: 'કેમેરા',
    voice: 'વોઇસ નોટ',
    drawing: 'ડ્રોઇંગ',
    delivery: 'ડિલિવરી',
    sample: 'સેમ્પલ',
    more: 'વધુ',
    yes: 'હા',
    ok: 'ઓકે',
    onMyWay: 'હું આવું છું',
    clientGroup: 'ક્લાયન્ટ ગ્રુપ',
    office: 'ઑફિસ',
    siteTeam: 'સાઇટ ટીમ',
    chat: 'ચેટ',
    sendSitePhoto: 'સાઇટનો ફોટો મોકલો',
    todayWord: 'આજે',
    yesterday: 'ગઈકાલે',
    officeOnly: 'આ ઑફિસ ચેટ છે. ક્લાયન્ટને દેખાશે નહીં.',
    people: 'લોકો',
  },
};

export function t(key) {
  const lang = (typeof sessionStorage !== 'undefined' && sessionStorage.getItem('field-lang')) || 'English';
  const pack = PACKS[lang] || ENGLISH;
  return pack[key] || ENGLISH[key] || key;
}
